[project]
name = "MatrixCurator"
version = "2025.6.1"
authors = [
    { name = "Shreya Jariwala", email = "sjariwala@morphobank.org" },
]

[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]