# LlamaCloud API Key
# Required for accessing LlamaParse.
# Obtain this key from your LlamaCloud account dashboard.
[llamacloud]
api_key = ""

# Langfuse Configuration
# Require for LLM promptS.
# Obtain these from your Langfuse project settings (e.g., app.langfuse.com).
[langfuse]
public_key = ""
secret_key = ""
host = ""

# Google Gemini API Key
# Required for accessing Google's Gemini family of models via their API.
# Obtain this key from Google AI Studio (https://aistudio.google.com/app/apikey)
[gemini]
api_key = ""

# Sentry DSN (Data Source Name)
# Optional: For error tracking and performance monitoring with Sentry (sentry.io).
# If you want to use Sentry, create a project in Sentry and find the DSN
# in your Sentry project settings (usually under "Client Keys (DSN)").
# If not using Sentry, this can be left blank or commented out.
[sentry] 
dsn = ""